CREATE TABLE `UPORABNIKI`(
  id INT NOT NULL AUTO_INCREMENT,
  uporabnisko_ime VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL,
  geslo_hash VARCHAR(255) NOT NULL,
  ime VARCHAR(50) NOT NULL,
  priimek VARCHAR(50) NOT NULL,
  profilna_slika VARCHAR(255),
  datum_registracije TIMESTAMP NOT NULL,
  vloga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `UPORABNIKI`
ADD CONSTRAINT `unq_uporabnisko_ime`
UNIQUE (`uporabnisko_ime`);

ALTER TABLE `UPORABNIKI`
MODIFY `datum_registracije` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `UPORABNIKI`
ADD CONSTRAINT `unq_email`
UNIQUE (`email`)

;


CREATE TABLE `KNJIGE`(
  id INT NOT NULL AUTO_INCREMENT,
  naslov VARCHAR(150) NOT NULL,
  jezik VARCHAR(50) NOT NULL,
  leto_izdaje YEAR,
  stevilka_izdaje INT,
  opis TEXT,
  dodana TIMESTAMP NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `KNJIGE`
MODIFY `dodana` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
;


CREATE TABLE `AVTORJI`(
  id INT NOT NULL AUTO_INCREMENT,
  ime VARCHAR(50) NOT NULL,
  priimek VARCHAR(50) NOT NULL,
  leto_rojstva YEAR,
  drzava VARCHAR(50),
  PRIMARY KEY(id)
);


CREATE TABLE `ZANRI`(
id INT NOT NULL AUTO_INCREMENT, naziv_zanra VARCHAR(100) NOT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE `OCENE`(
  id INT NOT NULL AUTO_INCREMENT,
  ocena INT NOT NULL,
  mnenje TEXT,
  ustvarjeno TIMESTAMP NOT NULL,
  uporabnik_id INT NOT NULL,
  knjiga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `OCENE`
ADD CONSTRAINT `chk_ocena` CHECK (`ocena` BETWEEN 1 AND 5);

ALTER TABLE `OCENE`
MODIFY `ustvarjeno` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `OCENE`
ADD CONSTRAINT `unq_ocene_uporabnik_knjiga`
UNIQUE (`uporabnik_id`, `knjiga_id`)
;


CREATE TABLE `KOMENTARJI`(
  id INT NOT NULL AUTO_INCREMENT,
  besedilo TEXT NOT NULL,
  ustvarjeno TIMESTAMP NOT NULL,
  izbrisan BOOLEAN NOT NULL,
  uporabnik_id INT NOT NULL,
  knjiga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `KOMENTARJI`
MODIFY `ustvarjeno` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `KOMENTARJI`
MODIFY `izbrisan` BOOLEAN NOT NULL DEFAULT FALSE
;


CREATE TABLE `VLOGE`(
id INT NOT NULL AUTO_INCREMENT, naziv_vloge VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);


CREATE TABLE `KNJIGE_AVTORJI`(
  id INT NOT NULL AUTO_INCREMENT,
  avtor_id INT NOT NULL,
  knjiga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `KNJIGE_AVTORJI`
ADD CONSTRAINT `unq_knjiga_avtor`
UNIQUE (`knjiga_id`, `avtor_id`)
;


CREATE TABLE `KNJIGE_ZANRI`(
  id INT NOT NULL AUTO_INCREMENT,
  zanr_id INT NOT NULL,
  knjiga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `KNJIGE_ZANRI`
ADD CONSTRAINT `unq_knjiga_zanr`
UNIQUE (`knjiga_id`, `zanr_id`)
;


CREATE TABLE `UPORABNIK_KNJIGE`(
  id INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(30) NOT NULL,
  datum_zacetka TIMESTAMP,
  datum_konca TIMESTAMP,
  ustvarjeno TIMESTAMP NOT NULL,
  uporabnik_id INT NOT NULL,
  knjiga_id INT NOT NULL,
  PRIMARY KEY(id)
);


ALTER TABLE `UPORABNIK_KNJIGE`
ADD CONSTRAINT `unq_uporabnik_knjiga`
UNIQUE (`uporabnik_id`, `knjiga_id`);

ALTER TABLE `UPORABNIK_KNJIGE`
MODIFY `ustvarjeno` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `UPORABNIK_KNJIGE`
ADD CONSTRAINT `chk_status`
CHECK (`status` IN ('zelim_prebrati', 'berem', 'prebrano'))
;


ALTER TABLE `UPORABNIKI`
  ADD CONSTRAINT `VLOGA_UPORABNIKI` FOREIGN KEY (vloga_id) REFERENCES `VLOGE` (id)
;


ALTER TABLE `KNJIGE_AVTORJI`
  ADD CONSTRAINT `AVTORJI_KNJIGE_AVTORJI`
    FOREIGN KEY (avtor_id) REFERENCES `AVTORJI` (id)
;


ALTER TABLE `KNJIGE_AVTORJI`
  ADD CONSTRAINT `KNJIGE_KNJIGE_AVTORJI`
    FOREIGN KEY (knjiga_id) REFERENCES `KNJIGE` (id)
;


ALTER TABLE `KNJIGE_ZANRI`
  ADD CONSTRAINT `ZANRI_KNJIGE_ZANRI`
    FOREIGN KEY (zanr_id) REFERENCES `ZANRI` (id)
;


ALTER TABLE `KNJIGE_ZANRI`
  ADD CONSTRAINT `KNJIGE_KNJIGE_ZANRI`
    FOREIGN KEY (knjiga_id) REFERENCES `KNJIGE` (id)
;


ALTER TABLE `UPORABNIK_KNJIGE`
  ADD CONSTRAINT `UPORABNIKI_UPORABNIK_KNJIGE`
    FOREIGN KEY (uporabnik_id) REFERENCES `UPORABNIKI` (id)
;


ALTER TABLE `UPORABNIK_KNJIGE`
  ADD CONSTRAINT `KNJIGE_UPORABNIK_KNJIGE`
    FOREIGN KEY (knjiga_id) REFERENCES `KNJIGE` (id)
;


ALTER TABLE `OCENE`
  ADD CONSTRAINT `UPORABNIKI_OCENE`
    FOREIGN KEY (uporabnik_id) REFERENCES `UPORABNIKI` (id)
;


ALTER TABLE `OCENE`
  ADD CONSTRAINT `KNJIGE_OCENE` FOREIGN KEY (knjiga_id) REFERENCES `KNJIGE` (id)
;


ALTER TABLE `KOMENTARJI`
  ADD CONSTRAINT `UPORABNIKI_KOMENTARJI`
    FOREIGN KEY (uporabnik_id) REFERENCES `UPORABNIKI` (id)
;


ALTER TABLE `KOMENTARJI`
  ADD CONSTRAINT `KNJIGE_KOMENTARJI`
    FOREIGN KEY (knjiga_id) REFERENCES `KNJIGE` (id)
;

